"""Add unique constraint and index to Project.title

Revision ID: 11b6d8bfa74e
Revises: 
Create Date: 2025-07-11 10:47:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '11b6d8bfa74e'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index('idx_project_title', ['title'], unique=False)
        batch_op.create_unique_constraint('uq_project_title', ['title'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_title', type_='unique')
        batch_op.drop_index('idx_project_title')
    # ### end Alembic commands ###