"""Add TaskDependency table for task dependencies

Revision ID: 306da7445ae9
Revises: 7dc3c7d646d0
Create Date: 2025-07-11 18:58:29.330427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306da7445ae9'
down_revision = '7dc3c7d646d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_task_dependency')
    )
    with op.batch_alter_table('task_dependency', schema=None) as batch_op:
        batch_op.create_index('idx_task_dependency_depends_on', ['depends_on_task_id'], unique=False)
        batch_op.create_index('idx_task_dependency_task', ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_dependency', schema=None) as batch_op:
        batch_op.drop_index('idx_task_dependency_task')
        batch_op.drop_index('idx_task_dependency_depends_on')

    op.drop_table('task_dependency')
    # ### end Alembic commands ###
